language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
    fast_finish: true
    include:
     - php: hhvm
       script: phpunit --testsuite integration

env:
 - EWAY_API_VERSION=31
 - EWAY_API_VERSION=40

cache:
    directories:
        - $HOME/.composer/cache

sudo: false

before_install:
  - composer self-update
  - composer validate

install:
  - travis_retry composer install --prefer-dist --no-interaction --optimize-autoloader
