name: PHP Quality Checks

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  extensions: mbstring, intl, json, curl, xdebug
  key: vendor

jobs:
  php-cs:
    name: PHP CodeSniffer
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run PHP Code Sniffer
        run: composer run phpcs

  phpstan:
    name: PHP Static Analysis
    runs-on: "ubuntu-24.04"

    steps:
      - uses: php-actions/phpstan@v3
      - uses: actions/checkout@v4

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: 8.4
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: ${{ env.extensions }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run phpstan
        uses: php-actions/phpstan@v3
        with:
          path: src/

  tests:
    name: PHP Tests (php=${{ matrix.php-version }}, api=${{ matrix.api-version }})
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        task:
          - unit
          - integration
        php-version:
          - 7.4
          - 8.0
          - 8.1
          - 8.2
          - 8.3
          - 8.4
        api-version:
          - 31
          - 40
          - 47

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.extensions }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPUnit - Unit Tests
        if: matrix.task == 'unit'
        env:
          EWAY_API_VERSION: ${{ matrix.api-version }}
        run: composer run test-unit

      - name: Run PHPUnit - Integration Tests
        if: matrix.task == 'integration'
        env:
          EWAY_API_VERSION: ${{ matrix.api-version }}
        run: composer run test-integration

      - name: Check 100% code coverage
        run: php .github/bin/check-coverage.php
